// Code generated by gobind. DO NOT EDIT.

// Java class hybridge.Hybridge is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java hybridge
package hybridge;

import go.Seq;

public abstract class Hybridge {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Hybridge() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * IsRunning 返回当前核心是否正在运行。
	 */
	public static native boolean isRunning();
	/**
	 * Start 启动 Hysteria2。
	会先校验 JSON 配置；成功返回空字符串，失败返回错误字符串。
	 */
	public static native String start(String configJSON);
	/**
	 * Stop 停止 Hysteria2。
	成功返回空字符串，失败返回错误字符串。
	 */
	public static native String stop();
	/**
	 * ValidateConfig 校验客户端 JSON 配置。
	返回空字符串表示成功；返回非空字符串表示失败原因。
	 */
	public static native String validateConfig(String configJSON);
}
